#!/usr/bin/env php
<?php
/**
 * @author Igor Vorobiov<igor.vorobioff@gmail.com>
 */

require __DIR__.'/vendor/autoload.php';

use ImmediateSolutions\Support\Framework\Console;
use ImmediateSolutions\Console\Support\ContainerRegister;

( new Console(new ContainerRegister()))->run();